### ISSUE TITLE
two repeated lines between modules.

### ISSUE THREAD

**Issue by matrixxun** [vanniktech/gradle-dependency-graph-generator-plugin#26]
When I use Generator API and `getModuleName` to filter my result, something very strange happened:
![d2fbc4b0-2c9a-4648-a736-95cf9764a627 1](https://user-images.githubusercontent.com/2074894/37470811-4b46a838-28a3-11e8-88c7-68d50984963f.png)
It's a bug?

**Comment by vanniktech** [comment]
If you give me an example and I can take a look at that then yes. Otherwise I don't think it's one. There's also a unit test for this. 

One reason for this might be due to the fact that dependencies are included multiple times or via different flavors / debugs. Can you share you build.gradle files?

**Comment by matrixxun** [comment]
you can try this google sample project: https://github.com/googlesamples/android-instant-apps/tree/master/multi-feature-module

The following figure is my test result by using generateDependencyGraph task:
![3027f762-0791-43f3-831c-17594774b1e0 1](https://user-images.githubusercontent.com/2074894/37472672-9fe68a6c-28a7-11e8-8663-e43a13e58308.png)

**Comment by vanniktech** [comment]
Thanks will do.

**Comment by vanniktech** [comment]
Fixed in #27. Thanks for the project. That one is a really good one.

**Comment by matrixxun** [comment]
I try 0.4.0-SNAPSHOT, It works now, excellent!
